<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.2 setup script
 * Date: Wed, 11 Dec 2019 15:29:11 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'wuhz2597';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'IKe(T+Quk?8S$xf2rSY}O/\\hCXb>D@Y';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>